# Generated by Django 3.1.2 on 2020-11-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
